version: '3.8'  # Specify the Compose file version

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    networks:
      - inception
    env_file: .env
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/
    ports:
      - "443:443"
    restart: always

  mariadb:
    image: mariadb
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_PASS=${DB_PASS}
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    restart: always
    expose:
      - "3306"

  wordpress:
    image: wordpress
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress:/var/www/
    networks:
      - inception
    env_file: .env
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/mbelouar/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: '/home/mbelouar/data/mariadb'

networks:
  inception:
    driver: bridge
